language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

before_script:
  - composer self-update
  - sudo apt-get update -qq
  - sudo apt-get install -qq zend-framework
  - mysql < tests/data/travis/db.structure.sql

script: 
  - composer install
  - phpunit

services:
  - redis-server
  - memcached
 
matrix:
  fast_finish: true
#  allow_failures:
#    - php: hhvm
    - php: hhvm-nightly
#    - php: 7.0

install:
  - tests/data/travis/memcached-setup.sh