language: php
sudo: false

env:
  - CODECLIMATE_REPO_TOKEN=20d76bff65cdc35b5d3450847800ecc6d5646842b55fe9b433cee1da0fa012ba PHP_OPTIONS="-d sendmail_path=`which true`"

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
#  - hhvm-nightly

before_script:
  - composer self-update
  - mysql < tests/data/travis/db.structure.sql

after_script:
#  - ./lib/vendor/bin/test-reporter

script: 
  - composer install
  - phpunit # --coverage-clover build/logs/clover.xml # Disabled

services:
  - redis-server
  - memcached

addons:
  mariadb: "10.0"
 
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly
    - php: hhvm
#    - php: 7.0

install:
  - tests/data/travis/memcached-setup.sh