language: php
php:
  - 5.5
  - 5.6
  - hhvm
before_script:
 - composer self-update
 - sudo apt-get update -qq
 - sudo apt-get install -qq zend-framework
 - mysql < db.dist/db.structure.travis.sql
script: 
 - composer install
 - phpunit
services:
 - redis-server